export const REGISTER_URL = import.meta.env.VITE_REGISTER_API_URL
export const LOGIN_URL = import.meta.env.VITE_LOGIN_API_URL
export const FETCH_ALL_PRODUCTS_URL = import.meta.env.VITE_PRODUCTS_API_URL


export const GET_CARTITEMS_COUNT_URL = import.meta.env.VITE_CART_COUNT_API_URL
export const ADD_ITEM_TO_CART_URL = import.meta.env.VITE_CART_ADD_PRODUCT_API_URL
export const GET_ALL_CARTITEMS_URL = import.meta.env.VITE_CART_GET_PRODUCTS_API_URL
export const UPDATE_CARTITEM_QUANTITY_URL = import.meta.env.VITE_UPDATE_CART_PRODUCTS_API_URL
export const DELETE_CARTITEM_URL = import.meta.env.VITE_DELETE_CART_PRODUCT_API_URL

export const CREATE_ORDER_ID = import.meta.env.VITE_PAYMENT_CREATE_ORDER_ID
export const VERIFY_SIGNATURE = import.meta.env.VITE_PAYMENT_VERIFY_SIGNATURE

export const FETCH_ALL_ORDERS = import.meta.env.VITE_FETCH_ALL_ORDERS

export const FETCH_PROFILE_URL = import.meta.env.VITE_FETCH_PROFILE
export const PROFILE_UPDATE_USERNAME_URL = import.meta.env.VITE_PROFILE_UPDATE_USERNAME
export const PROFILE_UPDATE_EMAIL_URL = import.meta.env.VITE_PROFILE_UPDATE_EMAIL
export const PROFILE_UPDATE_PASSWORD_URL = import.meta.env.VITE_PROFILE_UPDATE_PASSWORD