spring.application.name=backend

# Admin username
admin.username=Admin
admin.email=admin@gmail.com


# jwt secret key
jwt.secret = SG5BM6IQoLKBBnTvAb+A6KfcALNpXQE2iVeo3Jw1z7ZwxYNAiUl7hTFqz3f7Zb25IW7sxrbZNldNBnBQHvYxAQ==


# Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/ecom
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Razorpay keys
razorpay.key_id=rzp_test_SwSIA7CwgGQsib
razorpay.key_secret=79ixFvJAZhxzztTrS3bwuC0S

#Email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sendmail.service9@gmail.com
spring.mail.password=favowhzcsajlgcsh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true